[package]
name = "tonic-mock"
version.workspace = true
edition.workspace = true

[workspace]
members = [".", "tonic-mock-build"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
bytes = "1.4.0"
futures = "0.3.28"
futures-util = "0.3.28"
http = "0.2.9"
hyper = { version = "0.14.27", features = ["server", "http2", "http1", "runtime", "tcp", "stream"] }
prost = "0.11.9"
tokio = { version = "1.32.0", features = ["sync", "net"] }
tonic = "0.9.2"
tower = { version = "0.4.13", features = ["util"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = "0.1.37"

[build-dependencies]
tonic-mock-build = { path = "./tonic-mock-build" }

[dev-dependencies]
tokio = { version = "1.32.0", features = ["full"] }
tracing-test = "0.2.4"
